"use client";
import {useEffect,useMemo,useState} from "react";

type Districts={energy:number;mining:number;agri:number;industry:number;research:number};
type Planet={id:number;system:number;owner:number;name:string;climate:"temperate"|"arid"|"frozen";size:number;pop:number;housing:number;stability:number;crime:number;districts:Districts;buildings:string[];specialization:"balanced"|"forge"|"research"|"trade"|"agri";species:string;governor:string|null};
type Star={id:number;name:string;x:number;y:number;neighbors:number[];owner:number|null;surveyed:boolean;richness:number;habitable:boolean;station:boolean;fort:number;defense:number;devastation:number};
type Fleet={id:number;owner:number;name:string;system:number;ships:{corvette:number;frigate:number;cruiser:number};hp:number;army:number;design:{weapon:"kinetic"|"energy"|"missile";armor:"plating"|"shield"|"balanced"}};
type Relation={score:number;status:"peace"|"rival"|"war"|"alliance";claims:number[]};
type Discipline="physics"|"society"|"engineering";
type Tech={id:string;name:string;discipline:Discipline;tier:number;cost:number;rare:boolean;effect:string;prereq:string[];repeatable?:boolean;weight:number};
type Leader={id:number;owner:number;name:string;role:"scientist"|"admiral"|"governor";level:number;xp:number;trait:"analytical"|"bold"|"industrialist"|"diplomat"|"adaptable";assigned:number|null};
type Empire={id:number;name:string;credits:number;minerals:number;food:number;consumer:number;alloys:number;science:number;influence:number;unity:number;trade:number;systems:number[];tech:number;relations:Record<number,Relation>;government:"assembly"|"directorate"|"council"|"crown";policy:"growth"|"industry"|"science"|"military";species:string;ethic:"liberty"|"order"|"commerce"|"discovery";factions:{name:string;support:number;approval:number}[];research:Record<Discipline,{progress:number;active:string|null;choices:string[];completed:string[]}>;tradition:string|null;traditionProgress:number;traditions:string[];perks:string[]};
type War={a:number;b:number;goal:number|null;exhaustionA:number;exhaustionB:number;start:number};
type Game={turn:number;stars:Star[];planets:Planet[];empires:Empire[];fleets:Fleet[];leaders:Leader[];wars:War[];player:number;log:string[];selected:number|null;selectedPlanet:number|null;selectedFleet:number|null;nextFleet:number;nextPlanet:number;nextLeader:number};

const syl=["Ar","Bel","Cor","Dra","Eli","Fen","Gal","Hel","Iri","Jun","Ka","Lor","Mor","Nex","Ori","Pra","Qua","Ryn","Sol","Tor","Ul","Vor","Wen","Xan","Yor","Zen"];
const rn=(n:number)=>Math.floor(Math.random()*n),nm=()=>syl[rn(syl.length)]+syl[rn(syl.length)].toLowerCase()+rn(99);
const rel=(a:Empire,b:number):Relation=>a.relations[b]??(a.relations[b]={score:0,status:"peace",claims:[]});
const power=(f:Fleet,t:number,e?:Empire)=>Math.round((f.ships.corvette*3+f.ships.frigate*6+f.ships.cruiser*13)*(1+(t-1)*.12)*(f.hp/100)*(e?modifiers(e).fleetPower:1));
const jobs=(p:Planet)=>p.districts.energy*2+p.districts.mining*2+p.districts.agri*2+p.districts.industry*2+p.districts.research*2+p.buildings.length;

const TECH_FAMILIES:Record<Discipline,{family:string;effects:string[]}[]>={
 physics:[
 {family:"Field Theory",effects:["research output","sensor range","survey speed","energy output","shield strength","weapon accuracy"]},
 {family:"Particle Systems",effects:["energy weapons","reactor output","shield recovery","orbital power","beam tracking","fleet power"]},
 {family:"Computational Science",effects:["research alternatives","research speed","encryption","automation","targeting","strategic prediction"]},
 {family:"Spatial Dynamics",effects:["fleet movement","jump efficiency","hyperlane detection","exploration range","emergency transit","deep-space navigation"]},
 {family:"Quantum Engineering",effects:["rare discovery chance","sensor precision","energy efficiency","communications","advanced computation","late-game research"]},
 {family:"Astral Science",effects:["anomaly research","stellar harvesting","station output","deep survey","cosmic observation","exotic physics"]}
 ],
 society:[
 {family:"Genomic Science",effects:["population growth","habitability","food output","leader longevity","adaptation","species engineering"]},
 {family:"Civic Systems",effects:["unity output","stability","influence","crime reduction","faction approval","governance capacity"]},
 {family:"Xenological Studies",effects:["diplomatic relations","first contact","migration","trade diplomacy","alien integration","federated research"]},
 {family:"Behavioral Science",effects:["leader experience","governor effects","worker output","unrest resistance","policy efficiency","social cohesion"]},
 {family:"Planetary Ecology",effects:["food output","terraforming","devastation recovery","housing","colony growth","climate engineering"]},
 {family:"Strategic Society",effects:["army strength","war exhaustion","naval morale","defensive resolve","claim efficiency","wartime unity"]}
 ],
 engineering:[
 {family:"Materials Science",effects:["mineral output","armor strength","alloy output","building cost","hull durability","advanced materials"]},
 {family:"Voidcraft",effects:["ship cost","ship build speed","naval capacity","cruiser power","fleet upkeep","capital hulls"]},
 {family:"Industrial Systems",effects:["alloy output","district cost","consumer output","mining output","construction speed","industrial efficiency"]},
 {family:"Robotics",effects:["job output","automation","colony development","research assistance","hazard tolerance","synthetic labor"]},
 {family:"Fortification",effects:["starbase defense","ground defense","station cost","repair speed","bombardment resistance","fortress capacity"]},
 {family:"Macroconstruction",effects:["megaproject speed","station output","orbital construction","planetary works","resource storage","grand engineering"]}
 ]};
const ROMAN=["I","II","III","IV","V","VI"];
const TECHS:Tech[]=Object.entries(TECH_FAMILIES).flatMap(([discipline,families])=>(families as {family:string;effects:string[]}[]).flatMap((f,fi)=>f.effects.flatMap((effect,ei)=>Array.from({length:2},(_,variant)=>{
 const tier=Math.min(6,1+Math.floor(ei/1.15)),id=`${discipline.slice(0,2)}_${fi}_${ei}_${variant}`,prev=variant===1?`${discipline.slice(0,2)}_${fi}_${ei}_0`:ei>0?`${discipline.slice(0,2)}_${fi}_${ei-1}_1`:"";
 const adjectives=["Applied","Advanced","Integrated","Precision","Strategic","Frontier","Adaptive","Autonomous","Resonant","Quantum","Unified","Deep"];
 return{id,name:`${adjectives[(fi*3+ei+variant)%adjectives.length]} ${f.family} ${ROMAN[Math.min(5,tier-1)]}`,discipline:discipline as Discipline,tier,cost:55+tier*45+variant*20,rare:(ei===5&&variant===1)||(fi===5&&ei>=4),effect:`+${5+tier*2}% ${effect}`,prereq:prev?[prev]:[],weight:100-(tier*7)+(variant?0:8)};
 }))))).concat((["physics","society","engineering"] as Discipline[]).flatMap((d,di)=>Array.from({length:6},(_,i)=>({id:`repeat_${d}_${i}`,name:`Endless ${["Theory","Institutions","Fabrication"][di]} ${i+1}`,discipline:d,tier:6,cost:420+i*55,rare:i>3,effect:`Repeatable +${3+i}% ${["research and energy","unity and growth","alloys and fleet engineering"][di]}`,prereq:[],repeatable:true,weight:35}))));
const tech=(id:string)=>TECHS.find(t=>t.id===id)!;
const eligible=(e:Empire,t:Tech)=>t.prereq.every(x=>e.research[t.discipline].completed.includes(x))&&(t.repeatable||!e.research[t.discipline].completed.includes(t.id))&&t.tier<=Math.max(1,e.tech+1);
const choices=(e:Empire,d:Discipline)=>{
 const bonus=has(e,"inquiry","Data Commons")?1:0,rareBonus=has(e,"inquiry","Unorthodox Grants")?18:0;
 return TECHS.filter(t=>t.discipline===d&&eligible(e,t)).map(t=>({t,k:Math.random()*Math.max(1,t.weight+(t.rare?rareBonus:-0))})).sort((a,b)=>b.k-a.k).slice(0,3+bonus).map(x=>x.t.id);
};
const tech=(id:string)=>TECHS.find(t=>t.id===id)!;
type TraditionTree={id:string;name:string;theme:string;nodes:{name:string;effect:string}[];finisher:string};
const TRADITION_TREES:TraditionTree[]=[
["frontier","Frontier Mandate","Expansion and colonization",["Pioneer Corps|Colony cost -10%","Survey Authority|Survey rewards +15%","Orbital Charters|Claim cost -10%","Settlement Grants|Colony growth +10%","Deep Range Logistics|Fleet range efficiency +10%","New Horizons|New colonies begin stronger"],"Frontier Ascendant|Expansion infrastructure +15%"],
["industry","Industrial Engine","Heavy production",["Automated Foundries|Alloy output +8%","Deep Core Extraction|Minerals +10%","Fabrication Standards|Consumer output +10%","Industrial Zoning|District cost -10%","Throughput Doctrine|Industry jobs +10%","Reserve Stockpiles|Resource storage +25%"],"Forge Society|Industrial output +10%"],
["inquiry","Open Inquiry","Science and discovery",["Peer Networks|Research +8%","Field Institutes|Scientist XP +20%","Unorthodox Grants|Rare tech chance +10%","Data Commons|Research alternatives +1","Long Baselines|Survey speed +15%","Applied Theory|Technology cost -5%"],"Age of Reason|Research +10%"],
["warcraft","Strategic Command","Fleet warfare",["Officer Schools|Admiral XP +20%","Coordinated Fire|Fleet power +8%","Rapid Mobilization|Fleet cost -8%","Damage Control|Hull durability +10%","Operational Depth|Army capacity +20%","War Planning|War exhaustion gain -10%"],"Total Readiness|Fleet power +10%"],
["accord","Civic Accord","Stability and cohesion",["Public Trust|Stability +5","Local Councils|Unity +8%","Common Purpose|Faction approval +10","Social Guarantees|Crime -10","Mediation Corps|Unrest resistance +15%","Shared Identity|Influence +5%"],"Concordant Society|Stability +5"],
["commerce","Commercial Networks","Trade and markets",["Merchant Houses|Trade +12%","Open Exchanges|Credits +8%","Freight Standards|Trade +8%","Commercial Ports|Station income +10%","Contract Law|Building cost -8%","Venture Capital|Colony development +8%"],"Interstellar Market Culture|Trade +15%"],
["diplomacy","Interstellar Accord","Diplomacy and alliances",["Envoy Corps|Improve relations +20%","Mutual Guarantees|Alliance cohesion +15%","Cultural Missions|Trust growth +15%","Treaty Law|Diplomatic influence cost -15%","Joint Commands|Allied fleet coordination +10%","Open Channels|First contact speed +20%"],"Community Builder|Diplomatic weight +15%"],
["fortress","Bastion Doctrine","Defense and resilience",["Layered Defense|Starbase defense +15%","Civil Shelters|Bombardment damage -15%","Fortress Worlds|Ground defense +20%","Reserve Fleets|Defensive fleet power +10%","Hardened Networks|Sabotage resistance +20%","Last Line|Home defense +15%"],"Unbroken Line|All defenses +10%"],
["governance","Administrative Order","Government capacity",["Professional Service|Governor XP +20%","Regional Offices|Colony upkeep -8%","Census Bureau|Population output +5%","Executive Mandate|Policy effects +10%","Public Works|District cost -8%","Institutional Memory|Leader XP +10%"],"Capable State|Empire upkeep -8%"],
["adaptation","Adaptive Society","Harsh worlds and flexibility",["Climate Engineering|Habitability +10%","Flexible Labor|Job efficiency +5%","Mobile Housing|Housing +10%","Resilient Settlers|Colony stability +5","Emergency Protocols|Shortage penalties -20%","Ecological Mastery|Food +10%"],"Universal Settlers|Habitability +10%"],
["intelligence","Shadow Networks","Espionage and counterintelligence",["Cipher Office|Intel gain +15%","Quiet Assets|Operation cost -10%","Countercells|Enemy intel -15%","Black Channels|Covert speed +15%","Disinformation|Rival stability pressure +10%","Deep Cover|Asset discovery +20%"],"Invisible Hand|Espionage efficiency +15%"],
["leadership","Merit and Command","Leader development",["Talent Search|Leader pool +1","Mentorship|Leader XP +15%","Specialist Schools|Leader trait quality +10%","Long Service|Leader longevity +15%","Command Autonomy|Assigned leader effect +10%","Elite Cadres|Recruit cost -15%"],"Great Persons|Leader level cap +1"],
["logistics","Interstellar Logistics","Movement and supply",["Fleet Trains|Fleet upkeep -8%","Supply Depots|Army upkeep -10%","Navigation Corps|Movement efficiency +10%","Standard Containers|Trade +8%","Repair Tenders|Fleet repair +15%","Strategic Reserves|Alloy reserve efficiency +10%"],"Seamless Supply|Military upkeep -8%"],
["ecology","Living Worlds","Food, growth and planetary care",["Soil Renewal|Food +10%","Green Habitats|Housing +8%","Public Health|Growth +8%","Closed Loops|Consumer upkeep -8%","Restoration Corps|Devastation recovery +20%","Bioregional Planning|Stability +3"],"Flourishing Worlds|Growth and food +10%"],
["unity","Shared Destiny","Culture and unity",["Civic Rituals|Unity +10%","Public Archives|Tradition speed +10%","Cultural Houses|Faction approval +5","National Service|Influence +5%","Living Memory|Leader XP +8%","Common Story|Stability +3"],"One People|Unity +15%"],
["liberty","Free Polities","Autonomy and open society",["Local Autonomy|Colony stability +4","Free Press|Research +5%","Open Careers|Leader XP +10%","Civil Rights|Faction approval +8","Entrepreneurship|Trade +8%","Volunteer Defense|Defensive armies +10%"],"Open Civilization|Research and trade +6%"],
["authority","Central Mandate","Centralized control",["Direct Rule|Influence +8%","Production Quotas|Industry +8%","Security Bureau|Crime -12","Command Economy|Minerals +8%","Unified Planning|District cost -8%","State Service|Leader upkeep -10%"],"Central Power|Empire output +5%"],
["migration","Diaspora Networks","Migration and demographic growth",["Open Settlement|Growth +8%","Transit Hubs|Migration +15%","Cultural Bridges|Stability +3","Labor Mobility|Unemployment penalty -20%","New Citizens|Colony growth +10%","Remittance Webs|Trade +5%"],"Many Worlds One Society|Population output +6%"],
["engineering","Grand Works","Megaprojects and infrastructure",["Orbital Constructors|Station cost -10%","Planetary Works|District build cost -10%","Heavy Lift|Megaproject speed +10%","Modular Architecture|Building cost -10%","Structural Science|Engineering research +8%","Project Offices|Large project upkeep -10%"],"Builders of Ages|Megaproject capacity +1"],
["naval","Voidfaring","Shipbuilding and naval scale",["Dockyard Networks|Fleet build speed +15%","Standard Hulls|Ship cost -8%","Crew Rotation|Fleet upkeep -8%","Carrier Doctrine|Cruiser effectiveness +10%","Fleet Reserves|Naval capacity +15%","Veteran Crews|Admiral XP +15%"],"Masters of the Void|Fleet capacity +15%"],
["xenology","Plural Horizons","Alien relations and integration",["Translation Institutes|First contact +20%","Comparative Culture|Society research +8%","Exchange Programs|Relations +10","Plural Administration|Multi-species stability +5","Foreign Markets|Trade +8%","Shared Science|Alliance research +10%"],"Galactic Cosmopolitans|Diplomacy +10%"],
["transcendence","Beyond Biology","Late-game civilizational transformation",["Mind-Machine Interface|Leader effectiveness +8%","Directed Evolution|Population output +8%","Synthetic Organs|Leader longevity +20%","Collective Cognition|Research +8%","Post-Scarcity Design|Consumer upkeep -10%","Continuity Protocols|Leader loss penalty -50%"],"Transformed Civilization|All specialist output +8%"]
].map(([id,name,theme,raw,finish])=>({id:id as string,name:name as string,theme:theme as string,nodes:(raw as string[]).map(x=>{const [name,effect]=x.split("|");return{name,effect}}),finisher:(finish as string).split("|")[1]}));

type Mods={credits:number;minerals:number;food:number;consumer:number;alloys:number;research:number;unity:number;trade:number;influence:number;growth:number;stability:number;crime:number;districtCost:number;buildingCost:number;colonyCost:number;claimCost:number;fleetCost:number;fleetPower:number;leaderXp:number;warExhaustion:number;relations:number;housing:number;devRecovery:number};
const has=(e:Empire,tree:string,node:string)=>e.traditions.includes(tree+"::"+node);
const finished=(e:Empire,tree:string)=>{const t=TRADITION_TREES.find(x=>x.id===tree);return !!t&&e.perks.includes(t.name+" Finisher")};
function modifiers(e:Empire):Mods{
 const m:Mods={credits:1,minerals:1,food:1,consumer:1,alloys:1,research:1,unity:1,trade:1,influence:1,growth:1,stability:0,crime:0,districtCost:1,buildingCost:1,colonyCost:1,claimCost:1,fleetCost:1,fleetPower:1,leaderXp:1,warExhaustion:1,relations:1,housing:1,devRecovery:1};
 if(has(e,"industry","Automated Foundries"))m.alloys+=.08;if(has(e,"industry","Deep Core Extraction"))m.minerals+=.10;if(has(e,"industry","Fabrication Standards"))m.consumer+=.10;if(has(e,"industry","Industrial Zoning"))m.districtCost-=.10;if(finished(e,"industry")){m.alloys+=.10;m.minerals+=.10;m.consumer+=.10}
 if(has(e,"inquiry","Peer Networks"))m.research+=.08;if(finished(e,"inquiry"))m.research+=.10;
 if(has(e,"warcraft","Coordinated Fire"))m.fleetPower+=.08;if(has(e,"warcraft","Rapid Mobilization"))m.fleetCost-=.08;if(has(e,"warcraft","War Planning"))m.warExhaustion-=.10;if(finished(e,"warcraft"))m.fleetPower+=.10;
 if(has(e,"accord","Public Trust"))m.stability+=5;if(has(e,"accord","Local Councils"))m.unity+=.08;if(has(e,"accord","Social Guarantees"))m.crime-=10;if(has(e,"accord","Shared Identity"))m.influence+=.05;if(finished(e,"accord"))m.stability+=5;
 if(has(e,"commerce","Merchant Houses"))m.trade+=.12;if(has(e,"commerce","Open Exchanges"))m.credits+=.08;if(has(e,"commerce","Freight Standards"))m.trade+=.08;if(has(e,"commerce","Contract Law"))m.buildingCost-=.08;if(finished(e,"commerce"))m.trade+=.15;
 if(has(e,"diplomacy","Envoy Corps"))m.relations+=.20;if(finished(e,"diplomacy"))m.relations+=.15;
 if(has(e,"governance","Public Works"))m.districtCost-=.08;if(has(e,"governance","Institutional Memory"))m.leaderXp+=.10;
 if(has(e,"adaptation","Flexible Labor")){m.alloys+=.05;m.research+=.05}if(has(e,"adaptation","Mobile Housing"))m.housing+=.10;if(has(e,"adaptation","Resilient Settlers"))m.stability+=5;if(has(e,"adaptation","Ecological Mastery"))m.food+=.10;
 if(has(e,"leadership","Mentorship"))m.leaderXp+=.15;if(has(e,"leadership","Elite Cadres"))m.credits+=.02;
 if(has(e,"logistics","Strategic Reserves"))m.alloys+=.10;
 if(has(e,"ecology","Soil Renewal"))m.food+=.10;if(has(e,"ecology","Green Habitats"))m.housing+=.08;if(has(e,"ecology","Public Health"))m.growth+=.08;if(has(e,"ecology","Closed Loops"))m.consumer+=.08;if(has(e,"ecology","Restoration Corps"))m.devRecovery+=.20;if(has(e,"ecology","Bioregional Planning"))m.stability+=3;if(finished(e,"ecology")){m.food+=.10;m.growth+=.10}
 if(has(e,"unity","Civic Rituals"))m.unity+=.10;if(has(e,"unity","National Service"))m.influence+=.05;if(has(e,"unity","Living Memory"))m.leaderXp+=.08;if(has(e,"unity","Common Story"))m.stability+=3;if(finished(e,"unity"))m.unity+=.15;
 if(has(e,"liberty","Local Autonomy"))m.stability+=4;if(has(e,"liberty","Free Press"))m.research+=.05;if(has(e,"liberty","Open Careers"))m.leaderXp+=.10;if(has(e,"liberty","Entrepreneurship"))m.trade+=.08;if(finished(e,"liberty")){m.research+=.06;m.trade+=.06}
 if(has(e,"authority","Direct Rule"))m.influence+=.08;if(has(e,"authority","Production Quotas"))m.alloys+=.08;if(has(e,"authority","Security Bureau"))m.crime-=12;if(has(e,"authority","Command Economy"))m.minerals+=.08;if(has(e,"authority","Unified Planning"))m.districtCost-=.08;if(finished(e,"authority")){m.credits+=.05;m.minerals+=.05;m.alloys+=.05;m.research+=.05}
 if(has(e,"migration","Open Settlement"))m.growth+=.08;if(has(e,"migration","New Citizens"))m.growth+=.10;if(has(e,"migration","Remittance Webs"))m.trade+=.05;if(finished(e,"migration")){m.credits+=.06;m.minerals+=.06;m.food+=.06;m.alloys+=.06;m.research+=.06}
 if(has(e,"engineering","Planetary Works"))m.districtCost-=.10;if(has(e,"engineering","Modular Architecture"))m.buildingCost-=.10;if(has(e,"engineering","Structural Science"))m.research+=.08;
 if(has(e,"naval","Standard Hulls"))m.fleetCost-=.08;if(finished(e,"naval"))m.fleetPower+=.08;
 if(has(e,"xenology","Comparative Culture"))m.research+=.08;if(has(e,"xenology","Exchange Programs"))m.relations+=.10;if(has(e,"xenology","Foreign Markets"))m.trade+=.08;if(finished(e,"xenology"))m.relations+=.10;
 if(has(e,"transcendence","Mind-Machine Interface"))m.leaderXp+=.08;if(has(e,"transcendence","Directed Evolution")){m.credits+=.08;m.minerals+=.08;m.food+=.08;m.alloys+=.08;m.research+=.08}if(has(e,"transcendence","Collective Cognition"))m.research+=.08;if(has(e,"transcendence","Post-Scarcity Design"))m.consumer+=.10;if(finished(e,"transcendence")){m.alloys+=.08;m.research+=.08;m.unity+=.08}
 if(has(e,"frontier","Orbital Charters"))m.claimCost-=.10;if(has(e,"frontier","Settlement Grants"))m.growth+=.10;if(has(e,"frontier","Pioneer Corps"))m.colonyCost-=.10;if(finished(e,"frontier")){m.colonyCost-=.10;m.claimCost-=.05}
 const completed=(["physics","society","engineering"] as Discipline[]).flatMap(d=>e.research[d].completed.map(id=>tech(id)).filter(Boolean));
 for(const t of completed){const pct=(Number(t.effect.match(/\+(\d+)%/)?.[1]??0))/100,fx=t.effect.toLowerCase();
  if(fx.includes("research"))m.research+=pct;if(fx.includes("energy"))m.credits+=pct;if(fx.includes("mineral"))m.minerals+=pct;if(fx.includes("food"))m.food+=pct;if(fx.includes("alloy"))m.alloys+=pct;if(fx.includes("consumer"))m.consumer+=pct;if(fx.includes("unity"))m.unity+=pct;if(fx.includes("trade"))m.trade+=pct;if(fx.includes("growth"))m.growth+=pct;if(fx.includes("fleet power")||fx.includes("weapon")||fx.includes("cruiser"))m.fleetPower+=pct;if(fx.includes("ship cost")||fx.includes("fleet upkeep"))m.fleetCost-=pct;if(fx.includes("district cost"))m.districtCost-=pct;if(fx.includes("building cost"))m.buildingCost-=pct;if(fx.includes("claim"))m.claimCost-=pct;if(fx.includes("diplomatic"))m.relations+=pct;if(fx.includes("war exhaustion"))m.warExhaustion-=pct;if(fx.includes("housing"))m.housing+=pct;if(fx.includes("devastation"))m.devRecovery+=pct;
 }
 return m;
}

const spec=(p:Planet,k:keyof Districts)=>p.specialization==="forge"&&k==="industry"?1.25:p.specialization==="research"&&k==="research"?1.25:p.specialization==="agri"&&k==="agri"?1.25:p.specialization==="trade"&&k==="energy"?1.15:1;

function generate(count=900,ai=31):Game{
 const stars:Star[]=[];for(let i=0;i<count;i++)stars.push({id:i,name:nm(),x:40+Math.random()*1520,y:40+Math.random()*1120,neighbors:[],owner:null,surveyed:false,richness:1+rn(5),habitable:Math.random()<.18,station:false,fort:0,defense:0,devastation:0});
 for(let i=0;i<count;i++){const near=[...stars].filter(s=>s.id!==i).sort((a,b)=>Math.hypot(a.x-stars[i].x,a.y-stars[i].y)-Math.hypot(b.x-stars[i].x,b.y-stars[i].y)).slice(0,3+rn(3));for(const n of near){if(!stars[i].neighbors.includes(n.id))stars[i].neighbors.push(n.id);if(!stars[n.id].neighbors.includes(i))stars[n.id].neighbors.push(i)}}
 const gov=["assembly","directorate","council","crown"] as const,pol=["growth","industry","science","military"] as const,eth=["liberty","order","commerce","discovery"] as const;
 const empires:Empire[]=Array.from({length:ai+1},(_,id)=>({id,name:id===0?"Terran Dominion":nm()+" Compact",credits:220,minerals:160,food:100,consumer:80,alloys:100,science:0,influence:45,unity:0,trade:0,systems:[],tech:1,relations:{},government:gov[rn(4)],policy:pol[rn(4)],species:id===0?"Terran":nm()+"ian",ethic:eth[rn(4)],factions:[{name:"Prosperity Bloc",support:45,approval:60},{name:"Frontier League",support:30,approval:55},{name:"Security Forum",support:25,approval:50}],research:{physics:{progress:0,active:null,choices:[],completed:[]},society:{progress:0,active:null,choices:[],completed:[]},engineering:{progress:0,active:null,choices:[],completed:[]}},tradition:null,traditionProgress:0,traditions:[],perks:[]}));
 const planets:Planet[]=[],fleets:Fleet[]=[],leaders:Leader[]=[];const used=new Set<number>();let nextPlanet=0,nextLeader=0;
 for(const e of empires){let s=rn(count);while(used.has(s))s=rn(count);used.add(s);stars[s].owner=e.id;stars[s].surveyed=e.id===0;stars[s].station=true;e.systems.push(s);planets.push({id:nextPlanet++,system:s,owner:e.id,name:stars[s].name+" Prime",climate:["temperate","arid","frozen"][rn(3)] as Planet["climate"],size:14+rn(9),pop:10,housing:14,stability:65,crime:5,districts:{energy:1,mining:1,agri:1,industry:1,research:1},buildings:["Capital Complex"],specialization:"balanced",species:e.species,governor:null});fleets.push({id:e.id,owner:e.id,name:e.id===0?"1st Expeditionary Fleet":nm()+" Fleet",system:s,ships:{corvette:6,frigate:1,cruiser:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}});leaders.push({id:nextLeader++,owner:e.id,name:nm(),role:"scientist",level:1,xp:0,trait:"analytical",assigned:null},{id:nextLeader++,owner:e.id,name:nm(),role:"admiral",level:1,xp:0,trait:"bold",assigned:e.id},{id:nextLeader++,owner:e.id,name:nm(),role:"governor",level:1,xp:0,trait:"industrialist",assigned:planets[planets.length-1].id});for(const d of ["physics","society","engineering"] as Discipline[]){e.research[d].choices=choices(e,d);e.research[d].active=e.research[d].choices[0]??null}}
 for(const a of empires)for(const b of empires)if(a.id!==b.id)a.relations[b.id]={score:rn(41)-20,status:"peace",claims:[]};
 return{turn:1,stars,planets,empires,fleets,leaders,wars:[],player:0,log:["Your civilization enters the interstellar age. The economy is live."],selected:empires[0].systems[0],selectedPlanet:planets[0].id,selectedFleet:0,nextFleet:empires.length,nextPlanet,nextLeader};
}

function economy(g:Game,e:Empire){
 const ps=g.planets.filter(p=>p.owner===e.id),m=modifiers(e);let ec=0,min=0,food=0,con=0,alloy=0,sci=0,unity=0,trade=0;
 for(const p of ps){const employed=Math.min(p.pop,jobs(p)),eff=(.65+p.stability/200)*(1-p.devastation/150);ec+=p.districts.energy*5*spec(p,"energy")*eff;min+=p.districts.mining*5*spec(p,"mining")*eff;food+=p.districts.agri*6*spec(p,"agri")*eff;alloy+=p.districts.industry*3*spec(p,"industry")*eff;sci+=p.districts.research*4*spec(p,"research")*eff;trade+=p.pop*.35*(p.specialization==="trade"?1.5:1);unity+=p.buildings.filter(x=>x==="Civic Forum").length*3+1;con+=p.buildings.filter(x=>x==="Fabricator").length*3;p.crime=Math.max(0,Math.min(100,Math.round((p.pop-employed)*6+(50-p.stability)/3+m.crime)));p.stability=Math.max(20,Math.min(90,p.stability+(food>=ps.reduce((a,x)=>a+x.pop,0)*.35?1:-2)-(p.crime>30?1:0)+m.stability*.08));p.devastation=Math.max(0,p.devastation-m.devRecovery);if(food>0&&p.housing*m.housing>p.pop&&p.stability>45&&Math.random()<.22*m.growth)p.pop++}
 const pops=ps.reduce((a,p)=>a+p.pop,0);ec*=m.credits;min*=m.minerals;food*=m.food;con*=m.consumer;alloy*=m.alloys;sci*=m.research;unity*=m.unity;trade*=m.trade;e.credits+=ec+trade-pops*.35;e.minerals+=min;e.food+=food-pops*.45;e.consumer+=con-pops*.18;e.alloys+=alloy;e.science+=sci;e.unity+=unity;e.trade=trade;e.influence+=m.influence;
 if(e.food<0){e.food=0;for(const p of ps)p.stability-=3}if(e.consumer<0){e.consumer=0;for(const p of ps)p.stability-=2}
 if(e.science>=55*e.tech){e.science-=55*e.tech;e.tech++;if(e.id===0)g.log.unshift(`Technology tier ${e.tech} achieved.`)}
 for(const d of ["physics","society","engineering"] as Discipline[]){const r=e.research[d],active=r.active?tech(r.active):null;if(!active){r.choices=choices(e,d);r.active=r.choices[0]??null;continue}const scientist=g.leaders.find(l=>l.owner===e.id&&l.role==="scientist"),speed=1+(scientist?.level??0)*.04+(scientist?.trait==="analytical"?.1:0);r.progress+=sci/3*speed;if(r.progress>=active.cost){r.progress-=active.cost;if(!active.repeatable)r.completed.push(active.id);else r.completed.push(active.id);if(e.id===0)g.log.unshift(`Research completed: ${active.name} — ${active.effect}.`);if(scientist){scientist.xp+=20*modifiers(e).leaderXp;if(scientist.xp>=scientist.level*50){scientist.xp=0;scientist.level++}}r.choices=choices(e,d);r.active=r.choices[0]??null}}
 e.tech=1+Math.floor((e.research.physics.completed.length+e.research.society.completed.length+e.research.engineering.completed.length)/18);
 if(e.unity>=80){e.unity-=80;e.influence+=10;if(e.id===0)g.log.unshift("Civic cohesion generated 10 influence.")}
}

function battle(g:Game,system:number){const fs=g.fleets.filter(f=>f.system===system);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j];if(a.owner===b.owner||rel(g.empires[a.owner],b.owner).status!=="war")continue;const ap=power(a,g.empires[a.owner].tech,g.empires[a.owner]),bp=power(b,g.empires[b.owner].tech,g.empires[b.owner]);a.hp-=Math.min(100,Math.round(bp/Math.max(1,ap)*50));b.hp-=Math.min(100,Math.round(ap/Math.max(1,bp)*50));g.log.unshift(`Fleet battle at ${g.stars[system].name}.`)}g.fleets=g.fleets.filter(f=>f.hp>0)}

function tick(g:Game):Game{
 const n=structuredClone(g) as Game;n.turn++;
 for(const e of n.empires){economy(n,e);if(e.id!==0&&!e.tradition){const available=TRADITION_TREES.filter(t=>!e.perks.includes(t.name+" Finisher"));e.tradition=available[rn(available.length)]?.id??null}if(e.id===0)continue;const ps=n.planets.filter(p=>p.owner===e.id);if(ps.length&&e.minerals>=60*modifiers(e).districtCost&&Math.random()<.35){const p=ps[rn(ps.length)],keys=Object.keys(p.districts) as (keyof Districts)[];if(Object.values(p.districts).reduce((a,b)=>a+b,0)<p.size){p.districts[keys[rn(keys.length)]]++;e.minerals-=60*modifiers(e).districtCost}}const frontier=[...new Set(e.systems.flatMap(id=>n.stars[id].neighbors))].filter(id=>n.stars[id].owner===null);if(frontier.length&&e.influence>=8*modifiers(e).claimCost){const id=frontier[rn(frontier.length)];n.stars[id].owner=e.id;e.systems.push(id);e.influence-=8*modifiers(e).claimCost}if(e.alloys>=55*modifiers(e).fleetCost&&n.fleets.filter(f=>f.owner===e.id).length<Math.max(2,Math.ceil(e.systems.length/5))){e.alloys-=55*modifiers(e).fleetCost;n.fleets.push({id:n.nextFleet++,owner:e.id,name:nm()+" Fleet",system:e.systems[0],ships:{corvette:6,frigate:e.tech>1?2:0,cruiser:e.tech>2?1:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}})}}
 for(const w of n.wars){w.exhaustionA=Math.min(100,w.exhaustionA+.35*modifiers(n.empires[w.a]).warExhaustion);w.exhaustionB=Math.min(100,w.exhaustionB+.35*modifiers(n.empires[w.b]).warExhaustion)}
 if(n.turn%5===0)n.log.unshift(`Turn ${n.turn}: economy, populations and ${n.fleets.length} fleets simulated.`);localStorage.setItem("dominion-save-v8",JSON.stringify(n));return n;
}

export default function Home(){
 const[game,setGame]=useState<Game|null>(null),[tab,setTab]=useState("Galaxy"),[dip,setDip]=useState<number|null>(null);
 useEffect(()=>{const s=localStorage.getItem("dominion-save-v8");setGame(s?JSON.parse(s):generate())},[]);
 const p=game?.empires[0],selected=useMemo(()=>game?.stars.find(s=>s.id===game.selected)||null,[game]),planet=game?.planets.find(x=>x.id===game.selectedPlanet),sf=game?.fleets.find(f=>f.id===game.selectedFleet);
 if(!game||!p)return <main>Generating galaxy…</main>;
 const act=(fn:(g:Game)=>void)=>setGame(o=>{const n=structuredClone(o!) as Game;fn(n);localStorage.setItem("dominion-save-v8",JSON.stringify(n));return n});
 const selectSystem=(id:number)=>act(g=>{g.selected=id;const p=g.planets.find(x=>x.system===id);if(p)g.selectedPlanet=p.id});
 const survey=()=>selected&&act(g=>{g.stars[selected.id].surveyed=true});
 const claim=()=>selected&&act(g=>{const s=g.stars[selected.id],e=g.empires[0];const cost=8*modifiers(e).claimCost;if(s.owner===null&&s.surveyed&&e.influence>=cost){s.owner=0;e.systems.push(s.id);e.influence-=cost}});
 const colonize=()=>selected&&act(g=>{const s=g.stars[selected.id],e=g.empires[0];const cc=80*modifiers(e).colonyCost;if(s.owner===0&&s.habitable&&!g.planets.some(p=>p.system===s.id)&&e.credits>=cc&&e.food>=20){e.credits-=cc;e.food-=20;const np:Planet={id:g.nextPlanet++,system:s.id,owner:0,name:s.name+" Colony",climate:["temperate","arid","frozen"][rn(3)] as Planet["climate"],size:12+rn(12),pop:3,housing:8,stability:60,crime:0,districts:{energy:1,mining:0,agri:1,industry:0,research:0},buildings:["Colony Hub"],specialization:"balanced",species:e.species,governor:null};g.planets.push(np);g.selectedPlanet=np.id;g.log.unshift(`Colony founded on ${np.name}.`)}});
 const district=(k:keyof Districts)=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!,e=g.empires[0];const cost=60*modifiers(e).districtCost;if(q.owner===0&&e.minerals>=cost&&Object.values(q.districts).reduce((a,b)=>a+b,0)<q.size){q.districts[k]++;e.minerals-=cost}});
 const building=(b:string)=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!,e=g.empires[0];const cost=90*modifiers(e).buildingCost;if(q.owner===0&&e.minerals>=cost&&q.buildings.length<Math.max(2,Math.floor(q.pop/4)+1)){q.buildings.push(b);e.minerals-=cost;if(b==="Hab Complex")q.housing+=6}});
 const specialize=(s:Planet["specialization"])=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!;if(q.owner===0)q.specialization=s});
 const setPolicy=(x:Empire["policy"])=>act(g=>{g.empires[0].policy=x;g.log.unshift(`National policy shifted to ${x}.`)});
 const move=(to:number)=>sf&&act(g=>{const f=g.fleets.find(x=>x.id===sf.id);if(f&&g.stars[f.system].neighbors.includes(to)){f.system=to;g.stars[to].surveyed=true;g.selected=to;battle(g,to)}});
 const buildFleet=()=>act(g=>{const e=g.empires[0],cost=55*modifiers(e).fleetCost;if(e.alloys>=cost){e.alloys-=cost;g.fleets.push({id:g.nextFleet++,owner:0,name:`Task Force ${g.nextFleet}`,system:e.systems[0],ships:{corvette:6,frigate:e.tech>1?2:0,cruiser:e.tech>2?1:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}})}});
 const diplomacy=(id:number,kind:"improve"|"war"|"peace"|"alliance")=>act(g=>{const a=g.empires[0],b=g.empires[id],r=rel(a,id),br=rel(b,0);if(kind==="improve"&&a.influence>=5){a.influence-=5;r.score+=15*modifiers(a).relations;br.score=r.score}if(kind==="war"){r.status="war";br.status="war";g.wars.push({a:0,b:id,goal:r.claims[0]??null,exhaustionA:0,exhaustionB:0,start:g.turn})}if(kind==="peace"){r.status="peace";br.status="peace";g.wars=g.wars.filter(w=>!((w.a===0&&w.b===id)||(w.a===id&&w.b===0)))}if(kind==="alliance"&&r.score>=40){r.status="alliance";br.status="alliance"}});

 const selectTech=(d:Discipline,id:string)=>act(g=>{g.empires[0].research[d].active=id;g.empires[0].research[d].progress=0;g.log.unshift(`Research begun: ${tech(id).name}.`)});
 const chooseTradition=(id:string)=>act(g=>{const e=g.empires[0];if(!e.tradition&&!e.perks.includes(TRADITION_TREES.find(t=>t.id===id)?.name+" Finisher")){e.tradition=id;g.log.unshift(`${TRADITION_TREES.find(t=>t.id===id)?.name} tradition tree adopted.`)}});
 const recruit=(role:Leader["role"])=>act(g=>{const e=g.empires[0];if(e.credits>=75){e.credits-=75;const traits:Leader["trait"][]=["analytical","bold","industrialist","diplomat","adaptable"];g.leaders.push({id:g.nextLeader++,owner:0,name:nm(),role,level:1,xp:0,trait:traits[rn(traits.length)],assigned:null})}});
 return <main>
 <div className="top"><div className="brand"><h1>Dominion: Beyond the Stars</h1><p>Turn {game.turn} · {game.stars.length} systems · {game.empires.length} civilizations</p></div><button onClick={()=>setGame(tick(game))}>End Turn</button></div>
 <div className="statrow"><div className="stat"><b>{Math.floor(p.credits)}</b><span>Credits</span></div><div className="stat"><b>{Math.floor(p.minerals)}</b><span>Minerals</span></div><div className="stat"><b>{Math.floor(p.alloys)}</b><span>Alloys</span></div></div>
 <div className="statrow" style={{marginTop:8}}><div className="stat"><b>{Math.floor(p.food)}</b><span>Food</span></div><div className="stat"><b>{Math.floor(p.consumer)}</b><span>Consumer</span></div><div className="stat"><b>{Math.floor(p.influence)}</b><span>Influence</span></div></div>

 {tab==="Galaxy"&&<div className="grid two" style={{marginTop:10}}><div className="card"><div className="map"><div className="mapinner">{game.stars.flatMap(s=>s.neighbors.filter(n=>n>s.id).map(n=>{const t=game.stars[n],dx=t.x-s.x,dy=t.y-s.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return <div key={`l${s.id}-${n}`} className="line" style={{left:s.x,top:s.y,width:len,transform:`rotate(${ang}deg)`}}/>}))}{game.stars.map(s=><button key={s.id} aria-label={s.name} onClick={()=>selectSystem(s.id)} className={`star ${s.owner===0?"owned":s.owner!==null?"enemy":""} ${s.surveyed?"known":""}`} style={{left:s.x,top:s.y}}/>)}</div></div></div><div className="card"><h3>{selected?.name}</h3>{selected&&<><p className="muted">Owner: {selected.owner===null?"Unclaimed":game.empires[selected.owner].name} · Richness {selected.surveyed?selected.richness:"?"}<br/>Habitable: {selected.surveyed?(selected.habitable?"Yes":"No"):"Unknown"} · Devastation {selected.devastation}%</p><div className="actions"><button onClick={survey}>Survey</button><button onClick={claim}>Claim</button><button onClick={colonize}>Colonize</button></div>{sf&&game.stars[sf.system].neighbors.includes(selected.id)&&<button style={{width:"100%",marginTop:8}} onClick={()=>move(selected.id)}>Move {sf.name} here</button>}</>}</div></div>}

 {tab==="Empire"&&<><div className="card" style={{marginTop:10}}><h3>{p.name}</h3><p className="muted">{p.government} · {p.ethic} ethic · {p.species} primary species</p><div className="list"><div className="row"><span>Systems / Colonies</span><b>{p.systems.length} / {game.planets.filter(x=>x.owner===0).length}</b></div><div className="row"><span>Total population</span><b>{game.planets.filter(x=>x.owner===0).reduce((a,x)=>a+x.pop,0)}</b></div><div className="row"><span>Trade / Unity</span><b>{Math.floor(p.trade)} / {Math.floor(p.unity)}</b></div><div className="row"><span>Technology</span><b>{p.tech}</b></div></div><h4>National policy</h4><div className="actions">{(["growth","industry","science","military"] as const).map(x=><button key={x} className={p.policy===x?"active":""} onClick={()=>setPolicy(x)}>{x}</button>)}</div><h4>Active societal effects</h4><p className="muted">Research ×{modifiers(p).research.toFixed(2)} · Alloys ×{modifiers(p).alloys.toFixed(2)} · Trade ×{modifiers(p).trade.toFixed(2)} · Food ×{modifiers(p).food.toFixed(2)} · Fleet ×{modifiers(p).fleetPower.toFixed(2)} · Growth ×{modifiers(p).growth.toFixed(2)} · Stability +{modifiers(p).stability}</p><h4>Internal factions</h4>{p.factions.map(f=><div className="row" key={f.name}><span>{f.name}</span><small>{f.support}% support · {f.approval}% approval</small></div>)}</div>
 <div className="card" style={{marginTop:10}}><h3>Colonies</h3><div className="list">{game.planets.filter(x=>x.owner===0).map(q=><button key={q.id} onClick={()=>{act(g=>{g.selectedPlanet=q.id;g.selected=q.system});setTab("Planets")}}><b>{q.name}</b><br/><small>{q.pop} pop · stability {q.stability} · {q.specialization}</small></button>)}</div></div></>}

 {tab==="Planets"&&<div className="card" style={{marginTop:10}}><h3>{planet?.name||"Select a colony"}</h3>{planet&&<><p className="muted">{planet.climate} world · size {planet.size} · {planet.species}<br/>Population {planet.pop} · Housing {planet.housing} · Jobs {jobs(planet)} · Stability {planet.stability} · Crime {planet.crime}</p><h4>Specialization</h4><div className="actions">{(["balanced","forge","research","trade","agri"] as const).map(x=><button key={x} className={planet.specialization===x?"active":""} onClick={()=>specialize(x)}>{x}</button>)}</div><h4>Districts</h4><div className="actions">{(Object.keys(planet.districts) as (keyof Districts)[]).map(k=><button key={k} onClick={()=>district(k)}>{k} ({planet.districts[k]})</button>)}</div><h4>Buildings</h4><p className="muted">{planet.buildings.join(" · ")}</p><div className="actions"><button onClick={()=>building("Hab Complex")}>Hab Complex</button><button onClick={()=>building("Fabricator")}>Fabricator</button><button onClick={()=>building("Civic Forum")}>Civic Forum</button></div></>}</div>}

 {tab==="Fleets"&&<div className="card" style={{marginTop:10}}><h3>Fleet Command</h3><button onClick={buildFleet}>Commission Fleet (55 alloys)</button><div className="list" style={{marginTop:10}}>{game.fleets.filter(f=>f.owner===0).map(f=><button key={f.id} onClick={()=>{act(g=>{g.selectedFleet=f.id;g.selected=f.system});setTab("Galaxy")}}><b>{f.name}</b><br/><small>{game.stars[f.system].name} · power {power(f,p.tech,p)} · hull {f.hp}%</small></button>)}</div></div>}

 {tab==="Research"&&<><div className="card" style={{marginTop:10}}><h3>Research Directorate</h3><p className="muted">{TECHS.length} technologies · 3 disciplines · 6 tiers · prerequisite chains · rare and repeatable late-game research.</p>{(["physics","society","engineering"] as Discipline[]).map(d=>{const r=p.research[d],a=r.active?tech(r.active):null;return <div className="card" style={{marginTop:8}} key={d}><b>{d.toUpperCase()}</b><p>{a?a.name:"No project"} · {Math.floor(r.progress)}/{a?.cost??0}</p><div className="actions">{r.choices.map(id=><button key={id} className={r.active===id?"active":""} onClick={()=>selectTech(d,id)}>{tech(id).name}{tech(id).rare?" ★":""}<br/><small>Tier {tech(id).tier} · {tech(id).cost} research<br/>{tech(id).effect}</small></button>)}</div></div>})}</div>
 <div className="card" style={{marginTop:10}}><h3>Societal Traditions</h3><p className="muted">22 original trees · 132 individual tradition nodes. Complete six nodes to finish a tree, then choose another.</p>{p.tradition&&<p><b>Active:</b> {TRADITION_TREES.find(t=>t.id===p.tradition)?.name} · {Math.floor(p.traditionProgress)}/90 unity toward next node</p>}<div className="tradgrid">{TRADITION_TREES.map(t=>{const taken=p.traditions.filter(x=>x.startsWith(t.id+"::")).length,done=p.perks.includes(t.name+" Finisher");return <button key={t.id} className={p.tradition===t.id?"active":""} disabled={done||!!p.tradition&&p.tradition!==t.id} onClick={()=>chooseTradition(t.id)}><b>{t.name}</b><br/><small>{t.theme}<br/>{taken}/6 {done?"· COMPLETE":""}</small></button>})}</div>{p.tradition&&<div className="list" style={{marginTop:10}}>{TRADITION_TREES.find(t=>t.id===p.tradition)?.nodes.map((n,i)=>{const taken=p.traditions.includes(p.tradition+"::"+n.name);return <div className="row" key={n.name}><span>{taken?"✓ ":""}{n.name}<small><br/>{n.effect}</small></span><b>{i+1}/6</b></div>})}</div>}<p className="muted">Completed tree bonuses: {p.perks.join(" · ")||"none"}</p></div>
 <div className="card" style={{marginTop:10}}><h3>Leaders</h3><div className="actions"><button onClick={()=>recruit("scientist")}>Recruit Scientist (75)</button><button onClick={()=>recruit("admiral")}>Recruit Admiral (75)</button><button onClick={()=>recruit("governor")}>Recruit Governor (75)</button></div><div className="list" style={{marginTop:8}}>{game.leaders.filter(l=>l.owner===0).map(l=><div className="row" key={l.id}><span><b>{l.name}</b><br/><small>{l.role} · {l.trait}</small></span><span>Lv {l.level}<br/><small>{l.xp} XP</small></span></div>)}</div></div></>}

 {tab==="Diplomacy"&&<div className="card" style={{marginTop:10}}><h3>Diplomacy</h3><div className="list">{game.empires.slice(1).map(e=>{const r=rel(p,e.id);return <div key={e.id}><button style={{width:"100%"}} onClick={()=>setDip(dip===e.id?null:e.id)}>{e.name} · {r.status} · relations {r.score}</button>{dip===e.id&&<div className="actions"><button onClick={()=>diplomacy(e.id,"improve")}>Improve</button><button onClick={()=>diplomacy(e.id,"war")}>War</button><button onClick={()=>diplomacy(e.id,"peace")}>Peace</button><button onClick={()=>diplomacy(e.id,"alliance")}>Alliance</button></div>}</div>})}</div></div>}

 <div className="card" style={{marginTop:10}}><h3>Situation Log</h3><div className="log">{game.log.slice(0,40).map((x,i)=><div key={i}>{x}</div>)}</div></div>
 <div className="tabs six">{["Galaxy","Empire","Planets","Research","Fleets","Diplomacy"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
 </main>
}