"use client";
import {useEffect,useMemo,useState} from "react";

type Districts={energy:number;mining:number;agri:number;industry:number;research:number};
type Planet={id:number;system:number;owner:number;name:string;climate:"temperate"|"arid"|"frozen";size:number;pop:number;housing:number;stability:number;crime:number;districts:Districts;buildings:string[];specialization:"balanced"|"forge"|"research"|"trade"|"agri";species:string;governor:string|null};
type Star={id:number;name:string;x:number;y:number;neighbors:number[];owner:number|null;surveyed:boolean;richness:number;habitable:boolean;station:boolean;fort:number;defense:number;devastation:number};
type Fleet={id:number;owner:number;name:string;system:number;ships:{corvette:number;frigate:number;cruiser:number};hp:number;army:number;design:{weapon:"kinetic"|"energy"|"missile";armor:"plating"|"shield"|"balanced"}};
type Relation={score:number;status:"peace"|"rival"|"war"|"alliance";claims:number[]};
type Empire={id:number;name:string;credits:number;minerals:number;food:number;consumer:number;alloys:number;science:number;influence:number;unity:number;trade:number;systems:number[];tech:number;relations:Record<number,Relation>;government:"assembly"|"directorate"|"council"|"crown";policy:"growth"|"industry"|"science"|"military";species:string;ethic:"liberty"|"order"|"commerce"|"discovery";factions:{name:string;support:number;approval:number}[]};
type War={a:number;b:number;goal:number|null;exhaustionA:number;exhaustionB:number;start:number};
type Game={turn:number;stars:Star[];planets:Planet[];empires:Empire[];fleets:Fleet[];wars:War[];player:number;log:string[];selected:number|null;selectedPlanet:number|null;selectedFleet:number|null;nextFleet:number;nextPlanet:number};

const syl=["Ar","Bel","Cor","Dra","Eli","Fen","Gal","Hel","Iri","Jun","Ka","Lor","Mor","Nex","Ori","Pra","Qua","Ryn","Sol","Tor","Ul","Vor","Wen","Xan","Yor","Zen"];
const rn=(n:number)=>Math.floor(Math.random()*n),nm=()=>syl[rn(syl.length)]+syl[rn(syl.length)].toLowerCase()+rn(99);
const rel=(a:Empire,b:number):Relation=>a.relations[b]??(a.relations[b]={score:0,status:"peace",claims:[]});
const power=(f:Fleet,t:number)=>Math.round((f.ships.corvette*3+f.ships.frigate*6+f.ships.cruiser*13)*(1+(t-1)*.12)*(f.hp/100));
const jobs=(p:Planet)=>p.districts.energy*2+p.districts.mining*2+p.districts.agri*2+p.districts.industry*2+p.districts.research*2+p.buildings.length;
const spec=(p:Planet,k:keyof Districts)=>p.specialization==="forge"&&k==="industry"?1.25:p.specialization==="research"&&k==="research"?1.25:p.specialization==="agri"&&k==="agri"?1.25:p.specialization==="trade"&&k==="energy"?1.15:1;

function generate(count=900,ai=31):Game{
 const stars:Star[]=[];for(let i=0;i<count;i++)stars.push({id:i,name:nm(),x:40+Math.random()*1520,y:40+Math.random()*1120,neighbors:[],owner:null,surveyed:false,richness:1+rn(5),habitable:Math.random()<.18,station:false,fort:0,defense:0,devastation:0});
 for(let i=0;i<count;i++){const near=[...stars].filter(s=>s.id!==i).sort((a,b)=>Math.hypot(a.x-stars[i].x,a.y-stars[i].y)-Math.hypot(b.x-stars[i].x,b.y-stars[i].y)).slice(0,3+rn(3));for(const n of near){if(!stars[i].neighbors.includes(n.id))stars[i].neighbors.push(n.id);if(!stars[n.id].neighbors.includes(i))stars[n.id].neighbors.push(i)}}
 const gov=["assembly","directorate","council","crown"] as const,pol=["growth","industry","science","military"] as const,eth=["liberty","order","commerce","discovery"] as const;
 const empires:Empire[]=Array.from({length:ai+1},(_,id)=>({id,name:id===0?"Terran Dominion":nm()+" Compact",credits:220,minerals:160,food:100,consumer:80,alloys:100,science:0,influence:45,unity:0,trade:0,systems:[],tech:1,relations:{},government:gov[rn(4)],policy:pol[rn(4)],species:id===0?"Terran":nm()+"ian",ethic:eth[rn(4)],factions:[{name:"Prosperity Bloc",support:45,approval:60},{name:"Frontier League",support:30,approval:55},{name:"Security Forum",support:25,approval:50}]}));
 const planets:Planet[]=[],fleets:Fleet[]=[];const used=new Set<number>();let nextPlanet=0;
 for(const e of empires){let s=rn(count);while(used.has(s))s=rn(count);used.add(s);stars[s].owner=e.id;stars[s].surveyed=e.id===0;stars[s].station=true;e.systems.push(s);planets.push({id:nextPlanet++,system:s,owner:e.id,name:stars[s].name+" Prime",climate:["temperate","arid","frozen"][rn(3)] as Planet["climate"],size:14+rn(9),pop:10,housing:14,stability:65,crime:5,districts:{energy:1,mining:1,agri:1,industry:1,research:1},buildings:["Capital Complex"],specialization:"balanced",species:e.species,governor:null});fleets.push({id:e.id,owner:e.id,name:e.id===0?"1st Expeditionary Fleet":nm()+" Fleet",system:s,ships:{corvette:6,frigate:1,cruiser:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}})}
 for(const a of empires)for(const b of empires)if(a.id!==b.id)a.relations[b.id]={score:rn(41)-20,status:"peace",claims:[]};
 return{turn:1,stars,planets,empires,fleets,wars:[],player:0,log:["Your civilization enters the interstellar age. The economy is live."],selected:empires[0].systems[0],selectedPlanet:planets[0].id,selectedFleet:0,nextFleet:empires.length,nextPlanet};
}

function economy(g:Game,e:Empire){
 const ps=g.planets.filter(p=>p.owner===e.id);let ec=0,min=0,food=0,con=0,alloy=0,sci=0,unity=0,trade=0;
 for(const p of ps){const employed=Math.min(p.pop,jobs(p)),eff=(.65+p.stability/200)*(1-p.devastation/150);ec+=p.districts.energy*5*spec(p,"energy")*eff;min+=p.districts.mining*5*spec(p,"mining")*eff;food+=p.districts.agri*6*spec(p,"agri")*eff;alloy+=p.districts.industry*3*spec(p,"industry")*eff;sci+=p.districts.research*4*spec(p,"research")*eff;trade+=p.pop*.35*(p.specialization==="trade"?1.5:1);unity+=p.buildings.filter(x=>x==="Civic Forum").length*3+1;con+=p.buildings.filter(x=>x==="Fabricator").length*3;p.crime=Math.max(0,Math.min(100,Math.round((p.pop-employed)*6+(50-p.stability)/3)));p.stability=Math.max(20,Math.min(90,p.stability+(food>=ps.reduce((a,x)=>a+x.pop,0)*.35?1:-2)-(p.crime>30?1:0)));if(food>0&&p.housing>p.pop&&p.stability>45&&Math.random()<.22)p.pop++}
 const pops=ps.reduce((a,p)=>a+p.pop,0);e.credits+=ec+trade-pops*.35;e.minerals+=min;e.food+=food-pops*.45;e.consumer+=con-pops*.18;e.alloys+=alloy;e.science+=sci;e.unity+=unity;e.trade=trade;e.influence+=1;
 if(e.food<0){e.food=0;for(const p of ps)p.stability-=3}if(e.consumer<0){e.consumer=0;for(const p of ps)p.stability-=2}
 if(e.science>=55*e.tech){e.science-=55*e.tech;e.tech++;if(e.id===0)g.log.unshift(`Technology tier ${e.tech} achieved.`)}
 if(e.unity>=80){e.unity-=80;e.influence+=10;if(e.id===0)g.log.unshift("Civic cohesion generated 10 influence.")}
}

function battle(g:Game,system:number){const fs=g.fleets.filter(f=>f.system===system);for(let i=0;i<fs.length;i++)for(let j=i+1;j<fs.length;j++){const a=fs[i],b=fs[j];if(a.owner===b.owner||rel(g.empires[a.owner],b.owner).status!=="war")continue;const ap=power(a,g.empires[a.owner].tech),bp=power(b,g.empires[b.owner].tech);a.hp-=Math.min(100,Math.round(bp/Math.max(1,ap)*50));b.hp-=Math.min(100,Math.round(ap/Math.max(1,bp)*50));g.log.unshift(`Fleet battle at ${g.stars[system].name}.`)}g.fleets=g.fleets.filter(f=>f.hp>0)}

function tick(g:Game):Game{
 const n=structuredClone(g) as Game;n.turn++;
 for(const e of n.empires){economy(n,e);if(e.id===0)continue;const ps=n.planets.filter(p=>p.owner===e.id);if(ps.length&&e.minerals>=60&&Math.random()<.35){const p=ps[rn(ps.length)],keys=Object.keys(p.districts) as (keyof Districts)[];if(Object.values(p.districts).reduce((a,b)=>a+b,0)<p.size){p.districts[keys[rn(keys.length)]]++;e.minerals-=60}}const frontier=[...new Set(e.systems.flatMap(id=>n.stars[id].neighbors))].filter(id=>n.stars[id].owner===null);if(frontier.length&&e.influence>=8){const id=frontier[rn(frontier.length)];n.stars[id].owner=e.id;e.systems.push(id);e.influence-=8}if(e.alloys>=55&&n.fleets.filter(f=>f.owner===e.id).length<Math.max(2,Math.ceil(e.systems.length/5))){e.alloys-=55;n.fleets.push({id:n.nextFleet++,owner:e.id,name:nm()+" Fleet",system:e.systems[0],ships:{corvette:6,frigate:e.tech>1?2:0,cruiser:e.tech>2?1:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}})}}
 for(const w of n.wars){w.exhaustionA=Math.min(100,w.exhaustionA+.35);w.exhaustionB=Math.min(100,w.exhaustionB+.35)}
 if(n.turn%5===0)n.log.unshift(`Turn ${n.turn}: economy, populations and ${n.fleets.length} fleets simulated.`);localStorage.setItem("dominion-save-v4",JSON.stringify(n));return n;
}

export default function Home(){
 const[game,setGame]=useState<Game|null>(null),[tab,setTab]=useState("Galaxy"),[dip,setDip]=useState<number|null>(null);
 useEffect(()=>{const s=localStorage.getItem("dominion-save-v4");setGame(s?JSON.parse(s):generate())},[]);
 const p=game?.empires[0],selected=useMemo(()=>game?.stars.find(s=>s.id===game.selected)||null,[game]),planet=game?.planets.find(x=>x.id===game.selectedPlanet),sf=game?.fleets.find(f=>f.id===game.selectedFleet);
 if(!game||!p)return <main>Generating galaxy…</main>;
 const act=(fn:(g:Game)=>void)=>setGame(o=>{const n=structuredClone(o!) as Game;fn(n);localStorage.setItem("dominion-save-v4",JSON.stringify(n));return n});
 const selectSystem=(id:number)=>act(g=>{g.selected=id;const p=g.planets.find(x=>x.system===id);if(p)g.selectedPlanet=p.id});
 const survey=()=>selected&&act(g=>{g.stars[selected.id].surveyed=true});
 const claim=()=>selected&&act(g=>{const s=g.stars[selected.id],e=g.empires[0];if(s.owner===null&&s.surveyed&&e.influence>=8){s.owner=0;e.systems.push(s.id);e.influence-=8}});
 const colonize=()=>selected&&act(g=>{const s=g.stars[selected.id],e=g.empires[0];if(s.owner===0&&s.habitable&&!g.planets.some(p=>p.system===s.id)&&e.credits>=80&&e.food>=20){e.credits-=80;e.food-=20;const np:Planet={id:g.nextPlanet++,system:s.id,owner:0,name:s.name+" Colony",climate:["temperate","arid","frozen"][rn(3)] as Planet["climate"],size:12+rn(12),pop:3,housing:8,stability:60,crime:0,districts:{energy:1,mining:0,agri:1,industry:0,research:0},buildings:["Colony Hub"],specialization:"balanced",species:e.species,governor:null};g.planets.push(np);g.selectedPlanet=np.id;g.log.unshift(`Colony founded on ${np.name}.`)}});
 const district=(k:keyof Districts)=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!,e=g.empires[0];if(q.owner===0&&e.minerals>=60&&Object.values(q.districts).reduce((a,b)=>a+b,0)<q.size){q.districts[k]++;e.minerals-=60}});
 const building=(b:string)=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!,e=g.empires[0];if(q.owner===0&&e.minerals>=90&&q.buildings.length<Math.max(2,Math.floor(q.pop/4)+1)){q.buildings.push(b);e.minerals-=90;if(b==="Hab Complex")q.housing+=6}});
 const specialize=(s:Planet["specialization"])=>planet&&act(g=>{const q=g.planets.find(x=>x.id===planet.id)!;if(q.owner===0)q.specialization=s});
 const setPolicy=(x:Empire["policy"])=>act(g=>{g.empires[0].policy=x;g.log.unshift(`National policy shifted to ${x}.`)});
 const move=(to:number)=>sf&&act(g=>{const f=g.fleets.find(x=>x.id===sf.id);if(f&&g.stars[f.system].neighbors.includes(to)){f.system=to;g.stars[to].surveyed=true;g.selected=to;battle(g,to)}});
 const buildFleet=()=>act(g=>{const e=g.empires[0];if(e.alloys>=55){e.alloys-=55;g.fleets.push({id:g.nextFleet++,owner:0,name:`Task Force ${g.nextFleet}`,system:e.systems[0],ships:{corvette:6,frigate:e.tech>1?2:0,cruiser:e.tech>2?1:0},hp:100,army:3,design:{weapon:"kinetic",armor:"balanced"}})}});
 const diplomacy=(id:number,kind:"improve"|"war"|"peace"|"alliance")=>act(g=>{const a=g.empires[0],b=g.empires[id],r=rel(a,id),br=rel(b,0);if(kind==="improve"&&a.influence>=5){a.influence-=5;r.score+=15;br.score=r.score}if(kind==="war"){r.status="war";br.status="war";g.wars.push({a:0,b:id,goal:r.claims[0]??null,exhaustionA:0,exhaustionB:0,start:g.turn})}if(kind==="peace"){r.status="peace";br.status="peace";g.wars=g.wars.filter(w=>!((w.a===0&&w.b===id)||(w.a===id&&w.b===0)))}if(kind==="alliance"&&r.score>=40){r.status="alliance";br.status="alliance"}});

 return <main>
 <div className="top"><div className="brand"><h1>Dominion: Beyond the Stars</h1><p>Turn {game.turn} · {game.stars.length} systems · {game.empires.length} civilizations</p></div><button onClick={()=>setGame(tick(game))}>End Turn</button></div>
 <div className="statrow"><div className="stat"><b>{Math.floor(p.credits)}</b><span>Credits</span></div><div className="stat"><b>{Math.floor(p.minerals)}</b><span>Minerals</span></div><div className="stat"><b>{Math.floor(p.alloys)}</b><span>Alloys</span></div></div>
 <div className="statrow" style={{marginTop:8}}><div className="stat"><b>{Math.floor(p.food)}</b><span>Food</span></div><div className="stat"><b>{Math.floor(p.consumer)}</b><span>Consumer</span></div><div className="stat"><b>{Math.floor(p.influence)}</b><span>Influence</span></div></div>

 {tab==="Galaxy"&&<div className="grid two" style={{marginTop:10}}><div className="card"><div className="map"><div className="mapinner">{game.stars.flatMap(s=>s.neighbors.filter(n=>n>s.id).map(n=>{const t=game.stars[n],dx=t.x-s.x,dy=t.y-s.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return <div key={`l${s.id}-${n}`} className="line" style={{left:s.x,top:s.y,width:len,transform:`rotate(${ang}deg)`}}/>}))}{game.stars.map(s=><button key={s.id} aria-label={s.name} onClick={()=>selectSystem(s.id)} className={`star ${s.owner===0?"owned":s.owner!==null?"enemy":""} ${s.surveyed?"known":""}`} style={{left:s.x,top:s.y}}/>)}</div></div></div><div className="card"><h3>{selected?.name}</h3>{selected&&<><p className="muted">Owner: {selected.owner===null?"Unclaimed":game.empires[selected.owner].name} · Richness {selected.surveyed?selected.richness:"?"}<br/>Habitable: {selected.surveyed?(selected.habitable?"Yes":"No"):"Unknown"} · Devastation {selected.devastation}%</p><div className="actions"><button onClick={survey}>Survey</button><button onClick={claim}>Claim</button><button onClick={colonize}>Colonize</button></div>{sf&&game.stars[sf.system].neighbors.includes(selected.id)&&<button style={{width:"100%",marginTop:8}} onClick={()=>move(selected.id)}>Move {sf.name} here</button>}</>}</div></div>}

 {tab==="Empire"&&<><div className="card" style={{marginTop:10}}><h3>{p.name}</h3><p className="muted">{p.government} · {p.ethic} ethic · {p.species} primary species</p><div className="list"><div className="row"><span>Systems / Colonies</span><b>{p.systems.length} / {game.planets.filter(x=>x.owner===0).length}</b></div><div className="row"><span>Total population</span><b>{game.planets.filter(x=>x.owner===0).reduce((a,x)=>a+x.pop,0)}</b></div><div className="row"><span>Trade / Unity</span><b>{Math.floor(p.trade)} / {Math.floor(p.unity)}</b></div><div className="row"><span>Technology</span><b>{p.tech}</b></div></div><h4>National policy</h4><div className="actions">{(["growth","industry","science","military"] as const).map(x=><button key={x} className={p.policy===x?"active":""} onClick={()=>setPolicy(x)}>{x}</button>)}</div><h4>Internal factions</h4>{p.factions.map(f=><div className="row" key={f.name}><span>{f.name}</span><small>{f.support}% support · {f.approval}% approval</small></div>)}</div>
 <div className="card" style={{marginTop:10}}><h3>Colonies</h3><div className="list">{game.planets.filter(x=>x.owner===0).map(q=><button key={q.id} onClick={()=>{act(g=>{g.selectedPlanet=q.id;g.selected=q.system});setTab("Planets")}}><b>{q.name}</b><br/><small>{q.pop} pop · stability {q.stability} · {q.specialization}</small></button>)}</div></div></>}

 {tab==="Planets"&&<div className="card" style={{marginTop:10}}><h3>{planet?.name||"Select a colony"}</h3>{planet&&<><p className="muted">{planet.climate} world · size {planet.size} · {planet.species}<br/>Population {planet.pop} · Housing {planet.housing} · Jobs {jobs(planet)} · Stability {planet.stability} · Crime {planet.crime}</p><h4>Specialization</h4><div className="actions">{(["balanced","forge","research","trade","agri"] as const).map(x=><button key={x} className={planet.specialization===x?"active":""} onClick={()=>specialize(x)}>{x}</button>)}</div><h4>Districts</h4><div className="actions">{(Object.keys(planet.districts) as (keyof Districts)[]).map(k=><button key={k} onClick={()=>district(k)}>{k} ({planet.districts[k]})</button>)}</div><h4>Buildings</h4><p className="muted">{planet.buildings.join(" · ")}</p><div className="actions"><button onClick={()=>building("Hab Complex")}>Hab Complex</button><button onClick={()=>building("Fabricator")}>Fabricator</button><button onClick={()=>building("Civic Forum")}>Civic Forum</button></div></>}</div>}

 {tab==="Fleets"&&<div className="card" style={{marginTop:10}}><h3>Fleet Command</h3><button onClick={buildFleet}>Commission Fleet (55 alloys)</button><div className="list" style={{marginTop:10}}>{game.fleets.filter(f=>f.owner===0).map(f=><button key={f.id} onClick={()=>{act(g=>{g.selectedFleet=f.id;g.selected=f.system});setTab("Galaxy")}}><b>{f.name}</b><br/><small>{game.stars[f.system].name} · power {power(f,p.tech)} · hull {f.hp}%</small></button>)}</div></div>}

 {tab==="Diplomacy"&&<div className="card" style={{marginTop:10}}><h3>Diplomacy</h3><div className="list">{game.empires.slice(1).map(e=>{const r=rel(p,e.id);return <div key={e.id}><button style={{width:"100%"}} onClick={()=>setDip(dip===e.id?null:e.id)}>{e.name} · {r.status} · relations {r.score}</button>{dip===e.id&&<div className="actions"><button onClick={()=>diplomacy(e.id,"improve")}>Improve</button><button onClick={()=>diplomacy(e.id,"war")}>War</button><button onClick={()=>diplomacy(e.id,"peace")}>Peace</button><button onClick={()=>diplomacy(e.id,"alliance")}>Alliance</button></div>}</div>})}</div></div>}

 <div className="card" style={{marginTop:10}}><h3>Situation Log</h3><div className="log">{game.log.slice(0,40).map((x,i)=><div key={i}>{x}</div>)}</div></div>
 <div className="tabs six">{["Galaxy","Empire","Planets","Fleets","Diplomacy"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div>
 </main>
}